/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { SupplyChainNetworkContract } from "./SupplyChainNetwork";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "SupplyChainNetwork"): SupplyChainNetworkContract;
    }
  }
}

export {
  SupplyChainNetworkContract,
  SupplyChainNetworkInstance,
} from "./SupplyChainNetwork";
